[[main]]
  name = "Blog"
  url = ""
  weight = -110

[[main]]
  name = "Archivos"
  url = "post/archive/"
  weight = -109

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/OpenScienceLabs"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/opensciencelabs"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/company/open-science-labs/"
[[social]]
  name = "facebook"
  type = "social"
  url = "https://www.facebook.com/opensciencelabscommunity"
  weight = 4
[[social]]
  name = "discord"
  type = "social"
  url = "http://discord.opensciencelabs.org/"
  weight = 5
[[social]]
  name = "rss"
  weight = 6
  url = "index.xml"



# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://www.facebook.com/opensciencelabscommunity"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "http://discord.opensciencelabs.org/"